### PR TITLE
Support Pedagogy system for health statements 

### PR DESCRIPTION
**Pull request by bityob**
- [x] Add support for Pedagogy portal (used for kids in school) in addition for the parents portal (which should be for kids in kindergarten)
- [x] Refactor the code by splitting it to different methods with order
- [x] Updated some code variables to be like pep8 formatting (lowercase etc.)
- [x] Added todos file with ideas for new features and improvements

### CODE REVIEW

**Comment by bityob** [comment]
@AdamRussak @t0mer 

Updated the last todo (waiting for alert) and verified.

**Comment by AdamRussak** [comment]
hi @bityob first of all, great effort, and it is nice to see your enthusiasm!
but here are a few points we see we need to keep/ start in the project:

- [ ] keep OUR pre-stated Vars in the same name 
- [ ] the Selenium logic works as it is please remove the loops you did we know that it gots issues when more than 2 kids are in the list (stale Elements)
- [ ] each Covid-19 Approval site needs its own script and Bot command
- [ ] please see the PR #5  (he got some fixing too...), he will insert the Mashov command
+++
plese see our porject task for pointers/ ideas:
https://github.com/t0mer/Botvid-19/projects/1


@UdiMizrachi  please tag @bityob  once you got the PR ready.

**Comment by bityob** [comment]
Hey @AdamRussak,

> keep OUR pre-stated Vars in the same name

Will update the vars to use the same name all the way

> the Selenium logic works as it is please remove the loops you did we know that it gots issues when more than 2 kids are in the list (stale Elements)

For `Pedegogy` portal, loop is needed. 

There is a select input, and you need each time to choose another kid and checks all the checkboxes and approve for each one.
So, I need to use loop. And it works fine, verified multiple time (for my own kids).

 > each Covid-19 Approval site needs its own script and Bot command

Will split. But I think we don't need to run the logic from a script call, just put all it in an internal package and call the methods from the main bot module.

Do you have a reason why to call the logic with running a new script ant not just call the method directly?

**Comment by AdamRussak** [comment]
hi,
I am rejecting PR as we made many changes to our project.
if you wish to keep contribute please see the latest Branch: https://github.com/t0mer/Botvid-19/tree/adam/configYAML
and feel free to input to it.

*be aware* 
that I and @t0mer  are actively working on it, so there can be drastic changes that will render you work unnecessary at times (like this time)

**Pull request closed without merging**
