### PR TITLE
Use python3.8 and add logging

### PR DESCRIPTION
**Pull request by bityob**
Fixed comment from previous PR #1

### CODE REVIEW

**Comment by AdamRussak** [comment]
Looks good, will verify tomorrow that it works and if so will approve

**Comment by AdamRussak** [comment]
@bityob sorry, but can you fixe the Merge conflict (our fault not yours)

**Comment by bityob** [comment]
@AdamRussak  resolved conflicts

**Comment by bityob** [comment]
Verified.

Updated Dockerfile too with the renamed file name.

PR #3 didn't update the `chmod` command in the docker file

```
RUN echo 'export PATH="/opt/chromedriver-85.0.4183.87":$PATH' >> /root/.bashrc && chmod 777 /etc/Health_Statements.py
```

**Pull request merged**
